# Generated by Django 4.0.4 on 2022-06-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=80)),
                ('salary', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
