# Generated by Django 4.0.4 on 2022-06-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profilepic'),
        ),
    ]
